### PR TITLE
Rename types from AbstractPlotting.

### PR DESCRIPTION
**Pull request by adkabo**
AbstractPlotting renamed a bunch of things recently.
This change propagates those renames to AlgebraOfGraphics.

### CODE REVIEW

**Comment by adkabo** [comment]
I've only tested a bit manually. It seems okay so far.

**Comment by greimel** [comment]
the failure on 1.4 should be fixed by https://github.com/JuliaPlots/AbstractPlotting.jl/pull/601

@piever, the docs seem to be built for every PR. Do you know how to look at them?

**Comment by piever** [comment]
Thanks for doing this!

I wouldn't worry about the julia 1.4 failure: if it's a problem with loading AbstractPlotting, it is up to AbstractPlotting to put the bound on the julia version (or to fix, if it's easy enough).

The docs are generated at addresses like http://juliaplots.org/AlgebraOfGraphics.jl/previews/PR95/ (with the appropriate PR number), but unfortunately it only works if the PR comes from a branch of the JuliaPlots AlgebraOfGraphics repo, not from a fork.
For users working from their fork, I'm afraid the only way is to build the docs locally.

@adkabo this actually looks good to me, as the failure is unrelated. If you mark the PR as ready for review, I think it can be merged.

**Comment by adkabo** [comment]
Sure, marked as ready.

**Pull request merged**
