### PR TITLE
Support `GeometryBasics.AbstractGeometry` and `GeometryBasics.MultiPolygon`

### PR DESCRIPTION
**Pull request by greimel**
aog-map

```julia
using Pkg
pkg"activate polygons"
pkg"add Shapefile#sd/geometrybasics"
pkg"add AbstractPlotting#sd/geom_merge"
pkg"add GeometryBasics#sd/polygons"
pkg"add CairoMakie"
pkg"add https://github.com/greimel/CategoricalArrays#orderstyle" # EDIT: add this line

using Shapefile # for loading the data
using AbstractPlotting
using CairoMakie
using AlgebraOfGraphics

dir = "shp-dir"
if !isdir(dir)
    url_gadm = "https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_DEU_shp.zip"
    zip_archive = download(url_gadm) # 29 MB
  
    mkdir(dir)
    #dir = mktempdir()
    run(`unzip $zip_archive -d $dir`)
end

tbl_states = Shapefile.Table(joinpath(dir, "gadm36_DEU_1.shp"))
shp_states = tbl_states.Geometry

using DataFrames
df = tbl_states |> DataFrame

df[!,:z_var] = rand(size(df,1))
df[!,:grp] = rand([:grp1, :grp2, :grp3], size(df,1))

df # a DataFrame
categorical!(df, :Geometry) # Geometry is a vector of MultiPolygons

dta = data(df)
geom = spec(Poly)
aog = dta * geom * style(:Geometry, color = :grp)

dog |> draw
```

This needs to wait until a bug in AbstractPlotting is fixed. `plot!(ax, Poly, args...)` doesn't currently work.

EDIT:
It also needs JuliaData/CategoricalArrays.jl#292 because of https://github.com/JuliaData/CategoricalArrays.jl/issues/291

### CODE REVIEW

**Comment by piever** [comment]
Nice! Does this work out of the box just by doing `style(:geometry, color=:someproperty)`?

Also, I got a bit lost with all the GeometryBasics / GeoInterface changes, but is the name of the "geometry" (the column with all the polygons) always the same, regardless of whether it's a `MetaPoint`, `MetaPolygon`, or something else? (I only have a very vague understanding on the Geo / Geometry side of things.)

**Comment by greimel** [comment]
yes, I added runnable code above. So far I only tested it with `MultiPolynomial`, but in principle it should work with every object that AbstractPlotting can plot. (But only after this one bug mentioned above is fixed)

I guess one doesn't really need the Meta stuff, because you can just put the geometric objects in a DataFrame to hold your other data.

**Comment by greimel** [comment]
As an aside, I tried coloring with a continuous variable with this code. But it seems that this is not supported in general, right?

**Comment by piever** [comment]
> As an aside, I tried coloring with a continuous variable with this code. But it seems that this is not supported in general, right?

Mhm, I would have though that should work, will check later!

**Comment by greimel** [comment]
> As an aside, I tried coloring with a continuous variable with this code. But it seems that this is not supported in general, right?

never mind, it does work for simple cases. I need to check what goes wrong here.

**Comment by greimel** [comment]
Here is an update on this.

The branches in AbstractPlotting and GeometryBasics got merged and released, and so did my PR JuliaData/CategoricalArrays.jl#291. 

Note that the shapes are plain Vectors (no categorical vectors!). But they seem to be transformed to categorical vectors in the pipeline. That is why I needed to add this method for `replace_categorical`.

Here is a demonstration. (The map from above still works, the only branch that is still needed is for Shapefiles.jl)

## Homogenous shapes work

```julia
using AlgebraOfGraphics, AbstractPlotting, CairoMakie
using GeometryBasics, DataFrames

r1 = Point.([(2,2), (3,3)]) |> Rect
r2 = Point.([(0,0), (1,1)]) |> Rect
c1 = Circle(Point((2.0,2.0)), 2.0)
c2 = Circle(Point((0.0,0.0)), 1.0)
df1 = DataFrame(Geometry = [r1, r2], grp = categorical(["grp 1", "grp 2"]))
df2 = DataFrame(Geometry = [c1, c2], grp = categorical(["grp 1", "grp 2"]))

dta = data(df1)
geom = spec(Poly)
aog = dta * geom * style(:Geometry, color = :grp)

aog |> draw
```
fig

```julia
dta = data(df2)
geom = spec(Poly)
aog = dta * geom * style(:Geometry, color = :grp)

aog |> draw
```
fig2

## Mixed shapes don't work
```julia
df3 = [df1; df2]
dta = data(df3)
geom = spec(Poly)
aog = dta * geom * style(:Geometry, color = :grp)

aog |> draw
```
This is due to a limitation of AbstractPlotting: 

```julia
poly(df3.Geometry, color = 1:4)
```
<details>
    <summary>gives the error</summary>

```
There was no `AbstractPlotting.convert_arguments` overload found for
the plot type Scatter{...}, or its conversion trait AbstractPlotting.PointBased().
The arguments were:
(Array{GeometryBasics.GeometryPrimitive{2,T} where T,1},)

To fix this, define `AbstractPlotting.convert_arguments(::Scatter{...}, ::Array{GeometryBasics.GeometryPrimitive{2,T} where T,1})`.

error(::String) at error.jl:33
convert_arguments(::Type{Scatter{...}}, ::Array{GeometryBasics.GeometryPrimitive{2,T} where T,1}; kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at conversions.jl:46
convert_arguments(::Type{Scatter{...}}, ::Array{GeometryBasics.GeometryPrimitive{2,T} where T,1}) at conversions.jl:41
convert_arguments(::Type{Poly{...}}, ::Array{GeometryBasics.GeometryPrimitive{2,T} where T,1}) at basic_recipes.jl:46
plot!(::Scene, ::Type{Poly{...}}, ::Attributes, ::Array{GeometryBasics.GeometryPrimitive{2,T} where T,1}; kw_attributes::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at interfaces.jl:608
plot! at interfaces.jl:595 [inlined]
plot(::Type{Poly{...}}, ::Attributes, ::Array{GeometryBasics.GeometryPrimitive{2,T} where T,1}; kw_attributes::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at interfaces.jl:556
plot at interfaces.jl:553 [inlined]
#plot#192 at interfaces.jl:547 [inlined]
plot at interfaces.jl:546 [inlined]
#poly#293 at recipes.jl:12 [inlined]
(::AbstractPlotting.var"#poly##kw")(::NamedTuple{(:color,),Tuple{UnitRange{Int64}}}, ::typeof(poly), ::Array{GeometryBasics.GeometryPrimitive{2,T} where T,1}) at recipes.jl:12
top-level scope at aog.jl:163
include_string(::Function, ::Module, ::String, ::String) at loading.jl:1088
```
</details>

**Comment by greimel** [comment]
@piever sorry, the case with continuous styling doesn't work.

The problem is that Attributes contain a NamedArray that cannot be processed by AbstractPlotting.

My guess is that this happens because AoG thinks that the Geometries are categorical, so that they would be split eventually, but they aren't.

I cannot find the place where the Vector{Geometry} is transformed to a categorical array. Could you give me a hint where this happens?

**Comment by greimel** [comment]
@piever, should I open an issue at NamedDims about adding broadcasting style, or do you want to change the handling of attributes here?

Is there a reason that you save the attributes as named columns?

**Comment by greimel** [comment]
If the broadcasting bug for NamedDimArrays gets fixed, this can be merged from my side.

Here a demonstration with a local patch
```julia
using GeometryBasics, DataFrames

centers = 0:0.1:5
circs = [Circle(Point((c,c)), 0.05) for c in centers] 
df = DataFrame(x = centers, Geometry=circs)
data(df) * spec(Poly) * style(:Geometry, color=:x) |> draw
```
color

**Comment by greimel** [comment]
The two commits contain two different ways to get this working.

It depends a bit on how you think of categorical arrays. Do you want to convert shapes into a categorical array, or not?

**Comment by greimel** [comment]
Now that https://github.com/JuliaPlots/Makie.jl/issues/709 is solved, this branch works as it should.

<details><summary> Examples 1 and 2 (Maps) </summary>
 
```Julia
#using Pkg
#pkg"add Shapefile#sd/geometrybasics"

using Shapefile # for loading the data
using AbstractPlotting
using CairoMakie
using AlgebraOfGraphics

dir = "shp-dir"
if !isdir(dir)
    url_gadm = "https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_DEU_shp.zip"
    zip_archive = download(url_gadm) # 29 MB
  
    mkdir(dir)
    #dir = mktempdir()
    run(`unzip $zip_archive -d $dir`)
end

tbl_states = Shapefile.Table(joinpath(dir, "gadm36_DEU_1.shp"))
shp_states = tbl_states.Geometry

using DataFrames
df = tbl_states |> DataFrame

df[!,:z_var] = rand(size(df,1))
df[!,:grp] = rand([:grp1, :grp2, :grp3, :grp4], size(df,1)) |> categorical

dta = data(df)
geom = spec(Poly)

aog_c = dta * geom * style(:Geometry, color = :z_var)
aog_d = dta * geom * style(:Geometry, color = :grp)

aog_c |> draw
```
map-continuous

```julia
aog_d |> draw
```
map-categorical

</details>

<details><summary> Example 3 </summary>

```julia
using GeometryBasics, DataFrames

centers = 0:0.1:5
circs = [Circle(Point((c,c)), 0.05) for c in centers] 
df = DataFrame(x = centers, Geometry=circs)
data(df) * spec(Poly) * style(:Geometry, color=:x) |> draw
```
circles

<details>

As mentioned above, plotting heterogenous shapes doesn't work due to a bug in AbstractPlotting https://github.com/JuliaPlots/Makie.jl/issues/710.

I am looking forward to your review.

**Comment by piever** [comment]
Sorry for the slow response time, things have been a bit hectic on my side.

I like to keep attributes as named vectors, because I use that information for legends. I would actually like to drop the CategoricalArrays dependency at some point, but that's still a refactor away.

Concerning the example, I really think it should be the map. How far are we from getting that branch of Shape file merged?

**Comment by visr** [comment]
> How far are we from getting that branch of Shape file merged?

It's not quite there yet, and depends on a few other things, that should be released together, so still at least a month away. But it will get merged for sure.

**Comment by piever** [comment]
I'm merging this as is (version 2, do not convert Geometry stuff into categorical arrays). We should add the map example when there branch in Shapefile gets merged.

**Pull request merged**
