### PR TITLE
Use `RelocatableFolders` for font assets folders.

### PR DESCRIPTION
**Pull request by MichaelHatherly**
The current hardcoding of `@__DIR__` means that the package isn't usable with PackageCompiler when relocating system images since the source folders might not exist. This has come up before in Makie (where we solved it with `Artifacts`) and in `MathTeXEngine` (where we solved it with `RelocatableFolders` as done here). The `Artifacts` approach is a bit more involved to implement and maintain.

### CODE REVIEW

**Comment by vjd** [comment]
@piever can we request a quick review

**Comment by SimonDanisch** [comment]
@piever, I'll go ahead and merge + tag this, since the tests should be sufficient to "review" this ;) 
@MichaelHatherly, would it make sense to use the same for Makie? It looks like it does, and the artifact solution is pretty annoying ;)

**Comment by MichaelHatherly** [comment]
> @MichaelHatherly, would it make sense to use the same for Makie? It looks like it does, and the artifact solution is pretty annoying ;)

Yes, pretty annoying I'd say! I'll sort it out.

**Comment by piever** [comment]
Thanks for the PR and sorry for the delay in looking at this! 

LGTM, I'll merge and tag a patch release.

**Pull request merged**
